= Contributing

Contributors are always welcome!

Please consider that this project has been initiated by a beginner, so every input, recommendation or
correction is highly aprreciated.

ToDos
-----
- Write some developer guidance.
- Document feature **SliceArgv**
- Document feature **AsciiDoc generation**
- Document sub-feature **clean-package-elements** (in conjunction with `PostPack()`)
- Document `vc-utils`
- Isolate and document **string extensions**
- Mention Visual Studio Code related items (`--debug-vscode`, `launch.json`, `settings.json`)
- Remove the custom code for text coloring from PostPack() due to module `colors` now being included anyway.
- Find a smarter way to control verbose and debug output in `PostPack()` (ideally global handling of prefixes to fit output features in GitHub Actions as well as in Azure Runbooks).
- Add support for automatic versioning on publish.
- Make Resolve() in `generate-adoc.js` agjust `link:` directives (i.e. let the author link to subpaths as needed to test and afterwards adjust the link subpath, if needed).
- Think about renaming this package to `devtools` ...