# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Run publishing commands
        run: | 
          npm ci
          npm pack
          export NPM_TARBALL="$(cat NPM_TARBALL)"
          echo Publishing package [$NPM_TARBALL]
          npm publish "$NPM_TARBALL" --access public
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Increment Package Version
        run: node -e "require('./lib/update-package-version').UpdatePackageVersion('.', 'patch')"
      - name: List all environment variables (temporarily)
        run: set
        shell: bash
      - run: git status
      - run: git add "package.json"
      - run: git status
      - run: git commit -m "Automatic version patch increment after publish"
      - run: git status
